# Exported from Render on 2025-08-15T10:17:39Z
services:
- type: web
  name: musical-instruments-platform
  runtime: docker
  repo: https://github.com/stonsolabs/musical-instruments-platform
  plan: free
  envVars:
  - fromGroup: production_vars
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile
  domains:
  - www.getyourmusicgear.com
  - getyourmusicgear.com
  autoDeployTrigger: commit
version: "1"
