services:
  - type: web
    name: musical-instruments-backend
    runtime: docker
    repo: https://github.com/stonsolabs/musical-instruments-platform
    plan: free
    region: frankfurt
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    
    envVars:
      - fromGroup: backend_vars
    
    healthCheckPath: /health
    autoDeployTrigger: commit
    
    # Optional: Custom domains for the backend API
    # domains:
    #   - api.getyourmusicgear.com

version: "1"
