# Musical Instruments Platform - Render.com Deployment Configuration
# ================================================================

services:
  # Main web application
  - type: web
    name: musical-instruments-platform
    runtime: docker
    repo: https://github.com/stonsolabs/musical-instruments-platform
    plan: free
    region: frankfurt
    dockerContext: .
    dockerfilePath: ./Dockerfile
    
    # Environment variables from existing group
    envVars:
      - fromGroup: production_vars
    
    # Health check
    healthCheckPath: /health
    
    # Auto-deploy on commits
    autoDeployTrigger: commit
    
    # Custom domains
    domains:
      - www.getyourmusicgear.com
      - getyourmusicgear.com

version: "1"
